name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build APK
        run: |
          docker run --rm \
            --entrypoint /bin/bash \
            -v ${{ github.workspace }}:/home/user/hostcwd \
            -v ${{ github.workspace }}/.buildozer:/home/user/.buildozer \
            kivy/buildozer -c "
              yes | sdkmanager --licenses || true
              cd /home/user/hostcwd
              buildozer -v android debug
            "

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: KIRAYEDAAR-APK
          path: bin/*.apk
          if-no-files-found: warn
